oooo

diff --git a/load_balancer/1-install_load_balancer b/load_balancer/1-install_load_balancer
--- a/load_balancer/1-install_load_balancer
+++ b/load_balancer/1-install_load_balancer
@@ -1,28 +1,22 @@
 #!/usr/bin/env bash
-# Create a script to install and configure HAProxy on lb-01 server
-# Configure HAProxy to send traffic to web-01 and web-02 servers
-# Distribute requests using a roundrobin algorithm
-# Make sure that HAProxy can be managed via an init script
-# Install and configure HAproxy on my lb-01 server.
-sudo apt-get -y update
-apt-get -y install haproxy
+# Configure Nginx with custom HTTP header
 
-# edit config file
-server_config=\
-"
-frontend oreste-frontend
-        bind *:80
-        mode http
-        default_backend oreste-backend
-backend oreste-backend
-        balance roundrobin
-        server 6238-web-01 54.196.216.8:80 check
-        server 6238-web-02 98.80.15.59:80 check
-"
-echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
+# Update and install Nginx
+sudo apt update -y
+sudo apt install nginx -y
 
-# enable haproxy to be started by init script
+# code to add header to display hostname
+string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;"
+sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
 
-echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
+# Test Nginx configuration
+sudo nginx -t
 
-sudo service haproxy restart
+# If the test is successful, restart Nginx
+if [ $? -eq 0 ]; then
+    sudo service nginx restart
+    echo "Nginx configuration updated and restarted successfully."
+else
+    echo "Nginx configuration test failed. Please check the configuration."
+    exit 1
+fi
